import Foundation

/// A rule the on-device language model suggests based on observed
/// manual tagging behavior. Lives only in memory during a Suggest
/// session; on Accept it's converted to a `Rule` and sent through
/// `cli.saveRule`. On Skip it's added to the dismissed set so the
/// next analysis doesn't repropose it.
struct RuleSuggestion: Identifiable, Hashable {
    /// Stable per-suggestion id so SwiftUI ForEach doesn't churn
    /// when the user accepts/skips siblings.
    let id: UUID

    /// Short human-readable explanation of the pattern the model
    /// detected, e.g. "5 items from youtube.com tagged with #video".
    /// Shown above the proposed rule in the suggestion card.
    let pattern: String

    /// The proposed rule's name. Generated by the model from the
    /// pattern; the user can edit before saving.
    let name: String

    /// The matching criteria. Mirrors `RuleMatch` — only the relevant
    /// fields will be set for any given suggestion.
    let match: RuleMatch

    /// Tags to add when the rule fires. The most common (and currently
    /// only) action shape generated by this feature.
    let addTags: [String]

    /// IDs of items that exemplify the pattern. Surfaced in the card
    /// so the user can spot-check the suggestion ("does it actually
    /// belong to those items?") before accepting.
    let supportingItemIDs: [String]

    /// Convert to the canonical `Rule` shape for saving via the CLI.
    /// Saves as `enabled: false` by default so the user has to flip
    /// the toggle to activate — avoids surprise retroactive tagging.
    func toRule(enabled: Bool = false) -> Rule {
        Rule(
            name: name,
            description: pattern,
            enabled: enabled,
            match: match,
            actions: [RuleAction(addTags: addTags)]
        )
    }

    /// Stable fingerprint used to dedupe across analysis runs (so the
    /// "skipped patterns" set doesn't grow unbounded for cosmetically
    /// different proposals of the same rule). Domain + tags is the
    /// load-bearing signal; rule name varies more freely.
    var fingerprint: String {
        let domain = match.domain ?? ""
        let urlRegex = match.urlRegex ?? ""
        let type = match.type ?? ""
        let tagsKey = addTags.sorted().joined(separator: ",")
        return "\(type)|\(domain)|\(urlRegex)|\(tagsKey)"
    }
}
